name: egapx_runner
owner: fubar
categories:
- Genome annotation
- Sequence Analysis
description: Simple crude wrapper for entire egapx NF workflow as a Galaxy Tool
homepage_url: https://github.com/ncbi/egapx
long_description: |
 EGAPx is the publicly accessible version of the updated NCBI Eukaryotic Genome Annotation Pipeline.

 EGAPx takes an assembly fasta file, a taxid of the organism, and RNA-seq data. Based on the taxid, EGAPx will pick protein sets and HMM models. 
 The pipeline runs miniprot to align protein sequences, and STAR to align RNA-seq to the assembly. Protein alignments and RNA-seq read alignments 
 are then passed to Gnomon for gene prediction. In the first step of Gnomon, the short alignments are chained together into putative gene models. 
 In the second step, these predictions are further supplemented by ab-initio predictions based on HMM models. The final annotation for the input 
 assembly is produced as a gff file.
remote_repository_url: https://github.com/ncbi/egapx
type: unrestricted
